version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: logistica-casa-db
    environment:
      POSTGRES_DB: LogisticaCasa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend/LogisticaCasa.Backend.Api
      dockerfile: Dockerfile
    container_name: logistica-casa-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=LogisticaCasa;Username=user;Password=password
    depends_on:
      - db
    ports:
      - "5000:80"
volumes:
  postgres-data:
